### ISSUE TITLE
Content security policy error

### ISSUE THREAD

**Issue by stilian9205** [sojinantony01/react-cron-generator#1]
Hello, while I was using the component (great stuff by the way), everything was fine in dev, and when I built the app for production, I got the following error:

> Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-KpHv3zgivMSB4dPnfYfqMt2lBibsYvM36EdoBBAsfbM='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

I didn't get to any meaningfull answer so if you can lend me a hand in solving this I would appriciate it, I will post any code you need.

**Comment by stilian9205** [comment]
Answering my own question:  Including the CSS file creates the error, when you remove it everything works just fine. The problem was in your browserslist while minifying the CSS, you have to update your browserslist couse it is the one throwing the error.

**Comment by SojinAntony** [comment]
Everything working fine here in both development and build. I am trying to reproduce the issue.
