### ISSUE TITLE
Changing Tab also modifies the underlying cron value

### ISSUE THREAD

**Issue by WilliamPriorielloGarda** [sojinantony01/react-cron-generator#14]
Thanks for the nice tool. Here is an issue I found:

For example:
If my initial cron value is "every 5 minute(s)", and
I change tab from "Minutes" to "Hourly" and then back to "Minutes".

The cron value is now "Every 1 minute(s)".

Expected result:
The cron value should not change just because I changed tab

**Comment by sojinantony01** [comment]
This is the expected behavior for the current version

**Comment by WilliamPriorielloGarda** [comment]
Thanks for your fast responses and changes!

With regards to this enhancement, do you think it would be possible to have this functionality enabled as an optional (opt-in) feature passed as a prop? Maybe something like: changeCronOnTabChange?: false

thanks

**Comment by sojinantony01** [comment]
Please download the source code from this repo and convert the same base on your requirements, with the existing architecture it may cause some other issues if we implement the same, 
I will definitely try to add this feature
