### ISSUE TITLE
Console Warnings for componentWillMount and componentWillReceiveProps

### ISSUE THREAD

**Issue by WilliamPriorielloGarda** [sojinantony01/react-cron-generator#15]
The console logs two warnings for the usages of "componentWillMount" and "componentWillReceiveProps"

1)
> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Cron, HourlyCron

2)

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: Cron
>

**Comment by slimandslam** [comment]
These warnings are still there......

**Comment by bahare-enplore** [comment]
@sojinantony01 @slimandslam Did the components get updated? :) I'm getting the same warnings..

**Comment by sojinantony01** [comment]
life cycle methods renamed with UNSAFE_  functions.
