### ISSUE TITLE
Support for 6 character cron strings

### ISSUE THREAD

**Issue by WilliamPriorielloGarda** [sojinantony01/react-cron-generator#16]
From what I can tell, only 7 character cron strings are supported as of this time. If I set the value to a 6 character cron string, the tool seems to default to the picture below
![image](https://user-images.githubusercontent.com/66846208/85856156-78984580-b785-11ea-86ea-eab3bb8a93e7.png)

It also changes the cron string to an "every one minute" 7-character representation (0 0 00 1 1/1 ? *).

An example of a 6 character cron string that I am using: 0 15 1 ? * *

**Comment by SojinAntony** [comment]
@WilliamPriorielloGarda  Thanks for reporting. 
as of now this package only supports 7 character cron values. 
we can add this in the future
A pull request with 6 character cron support will be great.

**Comment by sojinantony01** [comment]
Added 6 char cron support

Thanks for reporting

**Comment by tamirCodefuel** [comment]
Hi guys, 

How do I change the output to a 6 characters cron expression?

**Comment by sojinantony01** [comment]
Currently, the output is always 7 char cron  
the last * in cron expression refers to year which 6 char cron doesn't have 

Please cut the last char from cron

**Comment by sojinantony01** [comment]
Currently, the output is always 7 char cron  
the last * in cron expression refers to year which 6 char cron doesn't have 

Please cut the last char from cron

**Comment by tamirCodefuel** [comment]
Thanks for your reply,
My question had came from what is seems as a non standard cron expression- 
when I generate a cron expression like every day at 6 I get - 0 0 06 1/1 * ? *
When our system and [cron guru](https://crontab.guru/) expect-  0 6 * * *
I thought that there might be a prop I can set it to our pattern.
