### ISSUE TITLE
Using only one header as option is throwing error

### ISSUE THREAD

**Issue by Sebashish** [sojinantony01/react-cron-generator#18]
`const options = {
    headers: [HEADER.MINUTES]
  };`

<img width="1767" alt="Screenshot 2020-07-10 at 12 41 15 PM" src="https://user-images.githubusercontent.com/38973944/87126933-b11e4000-c2aa-11ea-8f47-0a37438c3090.png">

**Note:**
- If state is empty then only it is throwing error.
- Setting up a default value will avoid this error (`const [value, setValue] = useState('0 0/6 * * * ? *');`)

**Comment by sojinantony01** [comment]
Yes You have to pass a default value (value) if you are customizing headers. The default value inside the Cron generator is for the Hourly tab and you are trying to hide the same. so please pass a default value of corresponding tabs to the corn generator.  The value  must match any of the available headers,  other vise corn will through some error

in Your case (MINUTES Tab) value can be :  (0 0/1 * * * ? * or any other Minutes corn value)
