### ISSUE TITLE
value does not match any available headers!!!

### ISSUE THREAD

**Issue by weieyuan** [sojinantony01/react-cron-generator#19]
After build code，the component.name is not correct.
![image](https://user-images.githubusercontent.com/16069074/87746964-868d3380-c824-11ea-9c82-b356c47eac4b.png)

**Comment by sojinantony01** [comment]
@weieyuan  Could you please share the value, selected header and available headers (if any)

**Comment by sojinantony01** [comment]
This issue is not reproducible. Please check the Document for correct usage
