### ISSUE TITLE
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends'

### ISSUE THREAD

**Issue by vasiliy-vdovichenko** [sojinantony01/react-cron-generator#20]
It shows following error on compile

  Module not found: Can't resolve '@babel/runtime/helpers/esm/extends'

the project is created with create-react-app and is not ejected.
It uses babel 7.9.0.
Looks like react-cron-generator is build with older version of babel which causes this problem

**Comment by sojinantony01** [comment]
Babel version updated
changed babel config 

Check latest version
