### ISSUE TITLE
Css does not working

### ISSUE THREAD

**Issue by stamahto** [sojinantony01/react-cron-generator#25]
Hi, I imported the css file from the package, but the component still shows no styles. Here is a live example. Thank you
[codesandbox](https://codesandbox.io/s/nifty-shannon-fqu1c?file=/src/App.js)

**Comment by SojinAntony** [comment]
@stamahto Please include Bootstrap in your index.html file
As I  mentioned in the Readme file
Package css is built over bootstrap

**Comment by stamahto** [comment]
Hi, thanks for quick response. Yes, I've tried before, but the changes are minimal. It is still not displayed correctly.
I've just updated codesandbox to see that.

**Comment by sojinantony01** [comment]
Please try with the old bootstrap version("bootstrap": "3.3.7")
We will update the package to the latest bootstrap version support
