### ISSUE TITLE
Css does not work on bootstrap 4.6.0 version.

### ISSUE THREAD

**Issue by Erkanerkisi** [sojinantony01/react-cron-generator#28]
Hello,

I am using bootstrap 4.6.0 version and component css does not work with it? I saw a post that you will upgrade bootstrap version 3 to 4? Is there any progress on that?

Thanks
Erkan

**Comment by Neilshweky** [comment]
Also having this problem, is there any update on this?

**Comment by sojinantony01** [comment]
Currently, it is running in bootstrap 3.4
And I am working on the update, changing the bootstrap version to 4.X
please expect an update in 2 or 3 days.
Thanks

**Comment by sojinantony01** [comment]
@Erkanerkisi  @Neilshweky 
Added bootstrap 4.X support
Please check the latest version


Thanks
Sojin

**Comment by Erkanerkisi** [comment]
will check and get back to you. Thanks
