### ISSUE TITLE
Global CSS cannot be imported from within node_modules. For nextjs

### ISSUE THREAD

**Issue by sfc-gh-vchandran** [sojinantony01/react-cron-generator#31]
I am using nextjs. On implementing cron, I am getting the error

./node_modules/react-cron-generator/dist/cron-builder.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-cron-generator/dist/cron.js

**Comment by sojinantony01** [comment]
@sfc-gh-vchandran 
Thanks for reporting this issue.
If Global CSS cannot be imported from within node_modules in nextJS 
please download the CSS file from this repository and add it to your project 
and import CSS file as a normal CSS file in your project 

CSS file link
https://github.com/sojinantony01/react-cron-generator/blob/master/src/lib/cron-builder.css
