### ISSUE TITLE
Wrong tab index on tab change

### ISSUE THREAD

**Issue by Cartales** [sojinantony01/react-cron-generator#32]
Hi,

I pass to options prop what header is not including MINITES, so it is defaultTabs index 0. My header options index 0 is Hourly. defaultValue function return metada index and metadata index 0 is always MINUTES but my header options index 0 is Hourly.
When i change tab to HOURLY, i receive MINUTES data because HOURLY index is 0 in my array but metadata index 0 is MINUTES.

**Comment by sojinantony01** [comment]
@Cartales 
Could you please share the prop values you passed to the corn generator?

**Comment by Cartales** [comment]
`import Cron from 'react-cron-generator';
import 'react-cron-generator/dist/cron-builder.css';
import { HEADER } from 'react-cron-generator';`

`const cronOptions = {
    headers: [HEADER.HOURLY, HEADER.DAILY, HEADER.WEEKLY, HEADER.MONTHLY],
  };`

`    <Cron
        onChange={(e) => changeScheduledTime(e)}
        value={triggerPayload?.expression}
        showResultText={true}
        options={cronOptions}
      />`

Sure you can see above.
I think index should receive value from defaultTabs array in meta.
`function defaultValue(tab) {
      var index = this.state.headers.indexOf(tab);

      if (metadata[index] === -1) {
        return;
      }

      return metadata[index].initialCron;
    }`

**Comment by sojinantony01** [comment]
Ok I understood
Thanks @Cartales 

Will update package

**Comment by sojinantony01** [comment]
@Cartales 
Updated the package
please check version "1.3.2"

Thanks
