### ISSUE TITLE
Cron expression in unix based format

### ISSUE THREAD

**Issue by jayaryan** [sojinantony01/react-cron-generator#36]
Cron expression output is basically a quartz style format having 7 no of fields. Is there any way to get it in a UNIX based style ( 5 or 6 no of field)

**Comment by sojinantony01** [comment]
Hi @jayaryan

Now package support 6 field cron expression inputs 
but when onchange only give 7 field expression
you can slice last value to convert to 6 field expression

**Comment by jayaryan** [comment]
Basically by the slicing way every 5 min (0 0/5 * * * ? *) will become (0 0/5 * * * ?) and 0 0/5 * * * ? will case a problem because of '?' i think.

**Comment by SojinAntony** [comment]
No it will  not
