### ISSUE TITLE
Cron generator Tabs are not retaining when we assigning the value in edit mode

### ISSUE THREAD

**Issue by vvrahul** [sojinantony01/react-cron-generator#37]
Cron generator Tabs are not retaining when we assigning the value in in our application (edit mode)

**Comment by sojinantony01** [comment]
Please provide  more details.  
which cron value you tried to assign? 
which tab is not retained?

**Comment by vvrahul** [comment]
Am using this package for sync schedule generator and am saving the  Cron value in the DB for  particular user and when user come back to this page am taking the Cron value from DB and assigning it back to the Cron component
` <Cron
        value={scheduledValue}
        showResultText={true}
        showResultCron={false}
        />`

scheduledValue is the Cron value and am not showing Cron  to user only the result text is showing . 

Suppose I have selected Monthly from the tab and save it to DB and again am coming back to the page and the Cron generator is showing Correct  result text. but the Tab which i have selected is not retaining its showing different tab preselected

**Comment by vvrahul** [comment]
There are a lot of crons 
**0 0/1 0 L * ? ***  for this, i have selected this  from the monthly tab (last day of Every month) but coming from

**Comment by vvrahul** [comment]
And one more thing i noticed that.. when i remove 
`
const syncSchedulerOptions = {
      headers: [HEADER.MONTHLY, HEADER.WEEKLY, HEADER.HOURLY, HEADER.DAILY, HEADER.CUSTOM]
    };
` Header options its working fine

**Comment by sojinantony01** [comment]
Closing the issue
as question is invalid
