### ISSUE TITLE
Incompatibility with the react 16.x version

### ISSUE THREAD

**Issue by mortezamt5** [sojinantony01/react-cron-generator#52]
./node_modules/react-cron-generator/build/index.js
Module not found: Can't resolve 'react/jsx-runtime' in '..\node_modules\react-cron-generator\build'
current react version is : 16.13.1
how cant I fix this bug ?

**Comment by sojinantony01** [comment]
Are you using any custom build procedure to start application ?

**Comment by bnuby** [comment]
@mortezamt5  You can temporary try this https://www.npmjs.com/package/@bnuby/react-cron-generator until the host make the updates.

I forked the project and make some changes to fix the issue.
only updated the `rollup.config.ts` to support `commonjs`

**Comment by valentinogiardino** [comment]
same here!

**Comment by sojinantony01** [comment]
Hi All, Kindly use version "1.3.13" for 16.X  react versions.
