### ISSUE TITLE
Coverage issues

### ISSUE THREAD

**Issue by linabru** [sojinantony01/react-cron-generator#6]
Getting:
```
node_modules\react-cron-generator\dist\monthly.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";
SyntaxError: Unexpected identifier
```

I think you should rename the .babelrc file to babel.config.js which will export .babelrc object.

**Comment by Felishanand** [comment]
How to enable the Header Like (['Minutes', 'Hourly', 'Daily', 'Weekly', 'Monthly'];) Option?

It seems, no property for handle above header, could you provide the option

**Comment by sojinantony01** [comment]
@Felishanand  You need to show few of these headers right ?

**Comment by ViswanathL** [comment]
@linabru  I think it is an issue with babel. Please check https://github.com/babel/babel/issues/10261

**Comment by sojinantony01** [comment]
@Felishanand  updated in latest version
