### ISSUE TITLE
Version 2.0.11 is overriding my styles

### ISSUE THREAD

**Issue by nadunc** [sojinantony01/react-cron-generator#62]
Recently I've upgraded to react-cron-generator version 2.0.11.
I've noticed it overrides my styles in the app, especially the fonts.

While searching for a solution, I found someone who had encountered the issue before, but there were no solutions provided. 
https://stackoverflow.com/questions/77670691/reactjs-imported-component-cron-overrides-styles

So, I fixed the problem and opened a pull request. @sojinantony01 Can you make another release with this change?
https://github.com/sojinantony01/react-cron-generator/pull/61

**Comment by sojinantony01** [comment]
Thanks @nadunc  
[61](https://github.com/sojinantony01/react-cron-generator/pull/61) - merged
Released a new version 2.0.12
