### ISSUE TITLE
Translate cron result

### ISSUE THREAD

**Issue by manuelsambade** [sojinantony01/react-cron-generator#66]
Hi!

I was able to translate the UI using translateFn prop.

However, how can I translate the result text?

For example: "At 12:00 AM, only on Monday and Wednesday"

![image](https://github.com/user-attachments/assets/3c4d9fe1-d1b8-472e-b986-f38135f0aa40)

Thanks

**Comment by manuelsambade** [comment]
I am using the following file to configure translations:

![image](https://github.com/user-attachments/assets/726afe2b-9889-42b3-a7fc-ecdc2d469f42)

**Comment by sojinantony01** [comment]
For the result genration package is using [cronstrue](https://github.com/bradymholt/cRonstrue) library

 locale option should be set for correct ResultText translation. 
 
 Please visit  for supported locales. - https://github.com/bradymholt/cRonstrue?tab=readme-ov-file#supported-locales
