### ISSUE TITLE
Cron Component's ResultText Lacks Internationalization Support

### ISSUE THREAD

**Issue by zhengchalei** [sojinantony01/react-cron-generator#70]
# Issue Title: Cron Component's ResultText Lacks Internationalization Support

## Description

While using the `<Cron>` component, I noticed that when `showResultText` is set to `true`, the explanatory text displayed below does not support internationalization. This could create barriers for users who are not operating in an English environment.

## Steps to Reproduce

1. Use the `<Cron>` component with `showResultText={true}` and `showResultCron={false}`.
2. Observe if the generated descriptive text supports language switching.

## Expected Behavior

I expect that when `showResultText` is set to `true`, the displayed text should be dynamically translated based on the user's language settings, rather than being limited to English only.

## Current Behavior

Currently, regardless of the user's language settings, the text displayed by `showResultText` remains in English.

## Possible Solution

A possible solution would be to extend the functionality of `translateFn` so that it also translates all descriptive texts that appear in `showResultText`.

### Example Code

```jsx
<Cron
    value={localValue}
    onChange={handleChange}
    showResultText={true}
    showResultCron={false}
    translateFn={(key: string) => {
      const map = {
          "Every": "每",
          "day(s)": "天（s）",
          "Every week day": "每个工作日",
          "Start time": "开始时间",
          "hour": "小时",
          "At": "在",
          "minute(s)": "分钟（s）",
          "Day": "日",
          "of every month(s)": "每月的",
          "Last day of every month": "每月的最后一天",
          "On the last weekday of every month": "每月的最后一个工作日",
          "day(s) before the end of the month": "月底前的天（s）",
          "Monday": "星期一",
          "Tuesday": "星期二",
          "Wednesday": "星期三",
          "Thursday": "星期四",
          "Friday": "星期五",
          "Saturday": "星期六",
          "Sunday": "星期日",
          "Minutes": "分钟",
          "Hourly": "每小时",
          "Daily": "每日",
          "Weekly": "每周",
          "Monthly": "每月",
          "Custom": "自定义",
          "Expression": "表达式"
      };
    return map[key] ?? key;
}}
/>

**Comment by sojinantony01** [comment]
Hi @zhengchalei 
The result text is actually coming from https://github.com/bradymholt/cRonstrue library  [npm](https://www.npmjs.com/package/cronstrue)

The steps to translate results is mentioned here - 
https://www.npmjs.com/package/react-cron-generator#:~:text=locale%20option%20should%20be%20set%20for%20correct%20ResultText%20translation.%20Please%20visit%20cronstrue%20for%20supported%20locales.

Here is an example with translated results - 

<img width="712" alt="Screenshot 2024-10-25 at 3 13 14 PM" src="https://github.com/user-attachments/assets/d793ccd5-1766-4c2e-821e-271279c073c2">


Pass locale variable to the cron component 
Supported locale are mentioned [here](https://github.com/bradymholt/cRonstrue?tab=readme-ov-file#supported-locales)

**Comment by zhengchalei** [comment]
> 你好@zhengchalei 结果文本实际上来自https://github.com/bradymholt/cRonstrue库 [npm](https://www.npmjs.com/package/cronstrue)
> 
> 翻译结果的步骤在此处提到 - https://www.npmjs.com/package/react-cron-generator#:~:text=locale%20option%20should%20be%20set%20for%20correct%20ResultText%20translation.%20Please%20visit%20cronstrue%20for%20supported%20locales。
> 
> 以下是翻译结果的示例 -
> 
> <img alt="截图于 2024-10-25 下午 3 点 13 分 14 秒" width="712" src="https://private-user-images.githubusercontent.com/29255847/380103493-d793ccd5-1766-4c2e-821e-271279c073c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTczODgsIm5iZiI6MTcyOTg1NzA4OCwicGF0aCI6Ii8yOTI1NTg0Ny8zODAxMDM0OTMtZDc5M2NjZDUtMTc2Ni00YzJlLTgyMWUtMjcxMjc5YzA3M2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDExNTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NjFlMzJlMGIxMGVlN2M0MTBiNmI5OGY2ZDcwZTA1MWIwYWZjOWM3N2ZmZTZiM2MxNTFkMDBjOGNjZmQ5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aZMTZHwFa3XlqnWVRr57p5AK6lIHFxA5rd_Xz66cS-0">
> 使用的区域设置是`locale="zh_CN"`
> 
> 将区域变量传递给`<Cron .... locale="zh_CN"/>`组件
> 
> [此处](https://github.com/bradymholt/cRonstrue?tab=readme-ov-file#supported-locales)提到了支持的语言环境[](https://github.com/bradymholt/cRonstrue?tab=readme-ov-file#supported-locales)

thank you

**Comment by zhengchalei** [comment]
> Hi @zhengchalei The result text is actually coming from https://github.com/bradymholt/cRonstrue library [npm](https://www.npmjs.com/package/cronstrue)
> 
> The steps to translate results are mentioned here - https://www.npmjs.com/package/react-cron-generator#:~:text=locale%20option%20should%20be%20set%20for%20correct%20ResultText%20translation.%20Please%20visit%20cronstrue%20for%20supported%20locales.
> 
> Here is an example with translated results -
> 
> <img alt="Screenshot 2024-10-25 at 3 13 14 PM" width="712" src="https://private-user-images.githubusercontent.com/29255847/380103493-d793ccd5-1766-4c2e-821e-271279c073c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTc0NTYsIm5iZiI6MTcyOTg1NzE1NiwicGF0aCI6Ii8yOTI1NTg0Ny8zODAxMDM0OTMtZDc5M2NjZDUtMTc2Ni00YzJlLTgyMWUtMjcxMjc5YzA3M2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDExNTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZTk2NjQzYjNlNTgyNWI5MDBiMWVlMDJiODA4OTAwNGEwZTRjMWMzNjIyZGJkODQ4MTVlYTY2YmQwNjFhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zmlqQIv1CfgSlSmJiQMCFQ1uVGbVlI3XMS2Q72_ZRQI">
> Locale used is `locale="zh_CN"`
> 
> Pass locale variable to the `<Cron .... locale="zh_CN"/>` component
> 
> Supported locale are mentioned [here](https://github.com/bradymholt/cRonstrue?tab=readme-ov-file#supported-locales)

thank you , (*￣︶￣)
