### ISSUE TITLE
Incorrect tab selection when passing daily cron string

### ISSUE THREAD

**Issue by DivyaChinthala** [sojinantony01/react-cron-generator#72]
I am encountering an issue when using the library to set up a cron schedule. When I select a daily schedule with a specific time, and then pass the same cron string back into the library, it automatically selects the "Hourly" tab instead of the "Daily" tab.

This behavior is incorrect because the cron string should be recognized as a daily schedule, and the library should select the "Daily" tab when the same cron string is passed.

**Steps to Reproduce:**

1. Select "Daily" schedule with a specific time (e.g., "0 11 13 1/1 * ? *").
2. Save the cron string and pass it back into the library.
3. The library automatically selects the "Hourly" tab, even though the string corresponds to a daily schedule.

**Expected Behavior:**
-    When passing a cron string like "0 11 13 1/1 * ? *", the library should select the "Daily" tab instead of the "Hourly" tab.

**Comment by sojinantony01** [comment]
Hi @DivyaChinthala,  if you look at cron value, Hourly `at` and Daily `Every` is same and it is generating very similar cron value. 
And by meaning also it is same
`0 11 13 1/1 * ? *` - Is every day At 01:11 PM
`0 11 13 1/1 * ? *` - At 01:11 PM

I don't think it is a major issue,
But to avoid confusion, i will try to find a way to differentiate the value.
