### ISSUE TITLE
Selecting multiple days in a month

### ISSUE THREAD

**Issue by shivam178** [sojinantony01/react-cron-generator#73]
Currently, the component only supports selecting one date in a month and not many. 
It gives an option to select the last day of every month and the last weekday of every month, but it would be better to support any other day at random by the user.

**Comment by sojinantony01** [comment]
> support any other day at random by the user.
Any other day can be already specified, but only one day 😄 

> the component only supports selecting one date in a month and not many.
Hmm!. yes Now it is only supporting a single day of month, 
And yes cron supports multiple values  `At 12:00 AM, on day 1, 2, and 3 of the month` - `0 0 00 3,2,1 1/1 ? *` I will try to fix this very soon. 

Thanks @shivam178

**Comment by roasted-tum0r** [comment]
Hi, I am interested to work in this enhancement. If I could get the hosted website URL and/or the filename and place where the enhancement needs to be done.

**Comment by sojinantony01** [comment]
I Addressed the issue in https://github.com/sojinantony01/react-cron-generator/pull/76
And updated the package version

@roasted-tum0r  Sorry, I already had started the work. 
If you are really interested in open source contributions please have a look in my other package todo list here - https://github.com/sojinantony01/react-spread-sheet
