### ISSUE TITLE
Weekly checkboxes labels should be clickable, with the cursor as a pointer!!

### ISSUE THREAD

**Issue by shivam178** [sojinantony01/react-cron-generator#74]
- I think we should have the checkbox labels as clickable; clicking on them selects the checkbox.
- The cursor should be a pointer when we hover over the label or checkbox.

https://github.com/user-attachments/assets/8a81c9e0-fbac-4ab1-8f6d-3de7d8f2465a

**Comment by shivam178** [comment]
If you think this is a good issue, I'll be happy to pick this up.

**Comment by sojinantony01** [comment]
@shivam178 
Yes, it can be added as in improvement. 
Feel free to create one PR.

**Comment by sojinantony01** [comment]
Thanks @shivam178 for the fix #75 .
I have published a version with the fix 2.0.15.
Feel free to close the issue once fix is confirmed in latest version

**Comment by shivam178** [comment]
Tested, looking good. Thanks, @sojinantony01.
