### ISSUE TITLE
CronProp importable

### ISSUE THREAD

**Issue by iqronfli** [sojinantony01/react-cron-generator#77]
I'm building a ChronoExpression generator using react-cron-generator, I need to access types. Is it possible to make exportable CronProp?

**Comment by sojinantony01** [comment]
Hi, I apologise for the delay happened.
Here is a PR to make CronProp importable - https://github.com/sojinantony01/react-cron-generator/pull/82

**Comment by sojinantony01** [comment]
https://www.npmjs.com/package/react-cron-generator/v/2.0.16
New version published
