### ISSUE TITLE
Monthly > Days of every month (comma-separated dates) > dates are not validated properly.

### ISSUE THREAD

**Issue by shivam178** [sojinantony01/react-cron-generator#78]
<img width="664" alt="Screenshot 2024-12-19 at 11 50 23 AM" src="https://github.com/user-attachments/assets/1e885c63-f8d8-4189-b201-6d23e726d694" />

In the image above, there are 2 more validations needed:
- 1 comma should be there at a time.
- Single date should not be repeated.

**Comment by shivam178** [comment]
I was thinking instead of asking the user for dates of a month in an input box, we can use `rc-dropdown` to open a dropdown to select multiple dates.

Pros:
- With that we can remove 2 input boxes in the monthly tab.
  - Selecting a single date of a month & selecting multiple dates in a month.
- No need to add more validation.
- Easy to use for end users.

Cons:
- We will rely on an outside library, although this library is small overall (59.6 minified bundled size).

Lemme know your thoughts. @SojinAntony.

**Comment by shivam178** [comment]
If this sounds good, I can pick this up.

**Comment by sojinantony01** [comment]
Yes, it is valid issue. we should improve that for usability. 
I am not full happy to use another external lib 😄 . but as a quick fix yes we can use it. 
But is it rc-dropdown or rc-select? 🤔, Or react-select

Only concern is The dropdown style need to matched with our existing input/dropdown boxes

**Comment by sojinantony01** [comment]
For normal date select we could use normal select box as we have in hours/minutes select
Only the multi select is something we need alterative!
Is there any way to have a simple multi select of our own solution 🤔

**Comment by sojinantony01** [comment]
I am trying an own dropdown solution, I will share an update EOD.

**Comment by sojinantony01** [comment]
I have created a draft PR - https://github.com/sojinantony01/react-cron-generator/pull/79
It is not ready, but you can test the multi select part

**Comment by sojinantony01** [comment]
https://www.npmjs.com/package/react-cron-generator/v/2.0.16
New version published
