### ISSUE TITLE
[feature request] localization support

### ISSUE THREAD

**Issue by allista** [sojinantony01/react-cron-generator#8]
Great tool, thanks for making it.
Unfortunately, it lacks any means to localize the component, as all the text is hard-coded.
So this is a feature request: to add a way to customize the text in the UI for non-english projects to be able to use it as well.

**Comment by sojinantony01** [comment]
Sure @allista. 
I will work on this ASAP 
Thanks.

**Comment by ViswanathL** [comment]
@allista Implemented the feature [Pull Request](https://github.com/sojinantony01/react-cron-generator/pull/12). @SojinAntony close this once merged

**Comment by sojinantony01** [comment]
Localization added in latest update. Thank you @ViswanathL

**Comment by Calfredop** [comment]
Please add localization for the header options.
Thanks

**Comment by SojinAntony** [comment]
@Calfredop  Hi. Thanks for reporting the issue 
Fixed in latest build. version  1.2.2
