### ISSUE TITLE
Should we export the `cronstrue` parse function from the library such that it is usable to others?

### ISSUE THREAD

**Issue by shivam178** [sojinantony01/react-cron-generator#81]
Should we export the function: `cronstrue.toString` such that the project using this dependency should not need to add the dependency `cronstrue` for parsing the string to words?

**Comment by sojinantony01** [comment]
I have just added `cronstrue` importable [here](https://github.com/sojinantony01/react-cron-generator/pull/82)
Please have a look

**Comment by sojinantony01** [comment]
https://www.npmjs.com/package/react-cron-generator/v/2.0.16
New version published
