### ISSUE TITLE
Showing different tab content after passing headers manually as options

### ISSUE THREAD

**Issue by kishankpatel** [sojinantony01/react-cron-generator#9]
First of all, I would like to thank you for the awesome plugin.

I am facing an issue with the plugin. Here are the details of the issue,

I tried to pass headers options with Monthly, Weekly, and Daily options, but it is always showing tab contents of the Hourly tab. It is working fine with options only if I pass options sequentially [HEADER.MINUTES, HEADER.HOURLY, HEADER.DAILY]

Here is my code sample,

  const cronHeaderOptions = {
    headers: [HEADER.MONTHLY, HEADER.WEEKLY, HEADER.DAILY]
  };

//-----

<Cron
  onChange={ (value)=> { setFieldValue('trigger_period', value) } }
  value={values.trigger_period}
  name="trigger_period"
  showResultText={true}
  options={cronHeaderOptions}
  />

![image](https://user-images.githubusercontent.com/19286677/80130104-b629f800-85b5-11ea-8d3f-81dbbc21ef94.png)

Please let me know if there is any configuration I am missing.
Thank you.

**Comment by kishankpatel** [comment]
Fixed the issue, please check
https://github.com/sojinantony01/react-cron-generator/pulls

**Comment by kishankpatel** [comment]
Thank you for accepting PR.

**Comment by sojinantony01** [comment]
But your fix  showing some error  in final build 
"component.name ". I am checking on that
Please check the same after build. I have added a few more lines for a quick fix.  checking to find the exact issue 
Thanks for the PR.

**Comment by sojinantony01** [comment]
The tab mismatch issue was occurred due to some other error. "Finding tab based on value" 
Will work on this soon

**Comment by kishankpatel** [comment]
ok, thank you.
